[*] Running ...
/home/dokhanhnam1199/.local/lib/python3.10/site-packages/numpy/_core/numeric.py:442: RuntimeWarning: invalid value encountered in cast
  multiarray.copyto(res, fill_value, casting='unsafe')
Traceback (most recent call last):
  File "/home/dokhanhnam1199/QD/problems/bpp_online/eval.py", line 112, in <module>
    avg_num_bins = -evaluate(dataset)
  File "/home/dokhanhnam1199/QD/problems/bpp_online/eval.py", line 55, in evaluate
    _, bins_packed = online_binpack(items.astype(float), bins)
  File "/home/dokhanhnam1199/QD/problems/bpp_online/eval.py", line 28, in online_binpack
    priorities = priority(item, bins[valid_bin_indices])
  File "/home/dokhanhnam1199/QD/problems/bpp_online/gpt.py", line 55, in priority_v2
    utilization_score = np.zeros_like(remaining_after_fit) # No comparison possible
numpy._core._exceptions._UFuncOutputCastingError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
41
4
