[*] Running ...
[*] Dataset loaded: C:\Users\Nam\Documents\GitHub\QD/problems/cvrp_aco\dataset/train50_dataset.npy with 10 instances.
[*] Instance 0: 18.63299035707662
[*] Instance 1: 20.318557994114396
[*] Instance 2: 21.091779686354105
[*] Instance 3: 19.759485702998727
[*] Instance 4: 19.644245293259306
[*] Instance 5: 20.12251537764478
[*] Instance 6: 17.945792337054947
[*] Instance 7: 21.004987047140446
[*] Instance 8: 18.01865585398493
[*] Instance 9: 19.844504701366166
[*] Average:
19.638351435099445
16
5
Traceback (most recent call last):
  File "C:\Users\Nam\Documents\GitHub\QD/problems/cvrp_aco/halstead.py", line 8, in <module>
    from utils.utils import get_heuristic_name
  File "C:\Users\Nam\Documents\GitHub\QD\outputs\main\hsevo-qd_cvrp_aco_2025-06-19_21-56-52\../../..\utils\utils.py", line 1, in <module>
    from litellm import completion
  File "C:\Users\Nam\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\__init__.py", line 340, in <module>
    model_cost = get_model_cost_map(url=model_cost_map_url)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nam\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\litellm_core_utils\get_model_cost_map.py", line 31, in get_model_cost_map
    response = httpx.get(
               ^^^^^^^^^^
  File "C:\Users\Nam\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_api.py", line 196, in get
    return request(
           ^^^^^^^^
  File "C:\Users\Nam\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_api.py", line 104, in request
    return client.request(
           ^^^^^^^^^^^^^^^
  File "C:\Users\Nam\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py", line 828, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nam\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py", line 915, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nam\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py", line 943, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nam\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py", line 980, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nam\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py", line 1016, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nam\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_transports\default.py", line 231, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nam\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpcore\_sync\connection_pool.py", line 268, in handle_request
    raise exc
  File "C:\Users\Nam\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpcore\_sync\connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nam\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpcore\_sync\connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nam\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpcore\_sync\connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nam\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpcore\_backends\sync.py", line 206, in connect_tcp
    sock = socket.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nam\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 837, in create_connection
    sock.connect(sa)
KeyboardInterrupt
