[*] Running ...
/home/dokhanhnam1199/QD/problems/bpp_online/gpt.py:26: RuntimeWarning: invalid value encountered in divide
  
/home/dokhanhnam1199/QD/problems/bpp_online/gpt.py:29: RuntimeWarning: invalid value encountered in cast
  
Traceback (most recent call last):
  File "/home/dokhanhnam1199/QD/problems/bpp_online/eval.py", line 112, in <module>
    avg_num_bins = -evaluate(dataset)
  File "/home/dokhanhnam1199/QD/problems/bpp_online/eval.py", line 55, in evaluate
    _, bins_packed = online_binpack(items.astype(float), bins)
  File "/home/dokhanhnam1199/QD/problems/bpp_online/eval.py", line 28, in online_binpack
    priorities = priority(item, bins[valid_bin_indices])
  File "/home/dokhanhnam1199/QD/problems/bpp_online/gpt.py", line 34, in priority_v2
    return priorities
numpy._core._exceptions._UFuncOutputCastingError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
16
2
274.72299342751836
