[*] Running ...
[*] Dataset loaded: /home/dokhanhnam1199/QD/problems/tsp_aco/dataset/train50_dataset.npy with 5 instances.
Traceback (most recent call last):
  File "/home/dokhanhnam1199/QD/problems/tsp_aco/eval.py", line 53, in <module>
    obj = solve(node_pos)
  File "/home/dokhanhnam1199/QD/problems/tsp_aco/eval.py", line 26, in solve
    heu = heuristics(dist_mat.copy()) + 1e-9
  File "/home/dokhanhnam1199/QD/problems/tsp_aco/gpt.py", line 45, in heuristics_v2
    connectivity_penalty = connectivity_penalty / np.max(connectivity_penalty) # Normalise to [0,1]
  File "numpy/random/mtrand.pyx", line 1576, in numpy.random.mtrand.RandomState.normal
  File "numpy/random/_common.pyx", line 637, in numpy.random._common.cont
  File "numpy/random/_common.pyx", line 435, in numpy.random._common.check_constraint
ValueError: scale < 0
11
3
101.95026032264605
