[*] Running ...
Traceback (most recent call last):
  File "/home/dokhanhnam1199/QD/problems/bpp_online/eval.py", line 112, in <module>
    avg_num_bins = -evaluate(dataset)
  File "/home/dokhanhnam1199/QD/problems/bpp_online/eval.py", line 55, in evaluate
    _, bins_packed = online_binpack(items.astype(float), bins)
  File "/home/dokhanhnam1199/QD/problems/bpp_online/eval.py", line 28, in online_binpack
    priorities = priority(item, bins[valid_bin_indices])
  File "/home/dokhanhnam1199/QD/problems/bpp_online/gpt.py", line 36, in priority_v2
    if np.all(remaining_capacities_after_fit[~is_best_fit] == remaining_capacities_after_fit[~is_best_fit][0]):
IndexError: index 0 is out of bounds for axis 0 with size 0
6
499.9129966509874
