[*] Running ...
[*] Dataset loaded: /home/dokhanhnam1199/QD/problems/cvrp_aco/dataset/train50_dataset.npy with 10 instances.
Traceback (most recent call last):
  File "/home/dokhanhnam1199/QD/problems/cvrp_aco/eval.py", line 60, in <module>
    obj = solve(node_pos, demand)
  File "/home/dokhanhnam1199/QD/problems/cvrp_aco/eval.py", line 33, in solve
    obj = aco.run(N_ITERATIONS)
  File "/home/dokhanhnam1199/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/dokhanhnam1199/QD/problems/cvrp_aco/aco.py", line 45, in run
    paths = self.gen_path()
  File "/home/dokhanhnam1199/QD/problems/cvrp_aco/aco.py", line 89, in gen_path
    actions = self.pick_move(actions, visit_mask, capacity_mask)
  File "/home/dokhanhnam1199/QD/problems/cvrp_aco/aco.py", line 101, in pick_move
    dist = Categorical(dist)
  File "/home/dokhanhnam1199/.local/lib/python3.10/site-packages/torch/distributions/categorical.py", line 73, in __init__
    super().__init__(batch_shape, validate_args=validate_args)
  File "/home/dokhanhnam1199/.local/lib/python3.10/site-packages/torch/distributions/distribution.py", line 72, in __init__
    raise ValueError(
ValueError: Expected parameter probs (Tensor of shape (30, 51)) of distribution Categorical(probs: torch.Size([30, 51])) to satisfy the constraint Simplex(), but found invalid values:
tensor([[nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        ...,
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan]], dtype=torch.float64)
29
6
162.84823041805248
