[*] Running ...
[*] Dataset loaded: /home/dokhanhnam1199/QD/problems/cvrp_aco/dataset/train50_dataset.npy with 10 instances.
/home/dokhanhnam1199/QD/problems/cvrp_aco/gpt.py:38: RuntimeWarning: invalid value encountered in scalar divide
Traceback (most recent call last):
  File "/home/dokhanhnam1199/QD/problems/cvrp_aco/eval.py", line 60, in <module>
    obj = solve(node_pos, demand)
  File "/home/dokhanhnam1199/QD/problems/cvrp_aco/eval.py", line 28, in solve
    heu = heuristics(dist_mat.copy(), node_pos.copy(), demand.copy(), CAPACITY) + 1e-9
  File "/home/dokhanhnam1199/QD/problems/cvrp_aco/gpt.py", line 41, in heuristics_v2
    total_distance += distance_matrix[route[i], route[i+1]]
  File "/usr/lib/python3.10/random.py", line 537, in choices
    raise ValueError('Total of weights must be finite')
ValueError: Total of weights must be finite
66
25
1005.1865670870906
