[*] Running ...
[*] Dataset loaded: /home/dokhanhnam1199/QD/problems/tsp_aco/dataset/train50_dataset.npy with 5 instances.
Traceback (most recent call last):
  File "/home/dokhanhnam1199/QD/problems/tsp_aco/eval.py", line 53, in <module>
    obj = solve(node_pos)
  File "/home/dokhanhnam1199/QD/problems/tsp_aco/eval.py", line 26, in solve
    heu = heuristics(dist_mat.copy()) + 1e-9
  File "/home/dokhanhnam1199/QD/problems/tsp_aco/gpt.py", line 32, in heuristics_v2
    selected_population = [population[i] for i in selected_indices]
  File "/home/dokhanhnam1199/QD/problems/tsp_aco/gpt.py", line 32, in <listcomp>
    selected_population = [population[i] for i in selected_indices]
IndexError: list index out of range
51
15
385.0
