[*] Running ...
[*] Dataset loaded: C:\Users\Nam\Documents\GitHub\HSEvo/problems/cvrp_aco\dataset/train50_dataset.npy with 10 instances.
Traceback (most recent call last):
  File "C:\Users\Nam\Documents\GitHub\HSEvo/problems/cvrp_aco/eval.py", line 60, in <module>
    obj = solve(node_pos, demand)
  File "C:\Users\Nam\Documents\GitHub\HSEvo/problems/cvrp_aco/eval.py", line 28, in solve
    heu = heuristics(dist_mat.copy(), node_pos.copy(), demand.copy(), CAPACITY) + 1e-9
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nam\Documents\GitHub\HSEvo\problems\cvrp_aco\gpt.py", line 59, in heuristics_v2
    mask = np.ones(n, dtype=bool)
                ~~^^^^^^^^^^^^^^^
  File "C:\Users\Nam\AppData\Roaming\Python\Python313\site-packages\numpy\lib\_function_base_impl.py", line 4504, in quantile
    return _quantile_unchecked(
        a, q, axis, out, overwrite_input, method, keepdims, weights)
  File "C:\Users\Nam\AppData\Roaming\Python\Python313\site-packages\numpy\lib\_function_base_impl.py", line 4517, in _quantile_unchecked
    return _ureduce(a,
                    func=_quantile_ureduce_func,
    ...<5 lines>...
                    overwrite_input=overwrite_input,
                    method=method)
  File "C:\Users\Nam\AppData\Roaming\Python\Python313\site-packages\numpy\lib\_function_base_impl.py", line 3848, in _ureduce
    r = func(a, **kwargs)
  File "C:\Users\Nam\AppData\Roaming\Python\Python313\site-packages\numpy\lib\_function_base_impl.py", line 4694, in _quantile_ureduce_func
    result = _quantile(arr,
                       quantiles=q,
    ...<2 lines>...
                       out=out,
                       weights=wgt)
  File "C:\Users\Nam\AppData\Roaming\Python\Python313\site-packages\numpy\lib\_function_base_impl.py", line 4816, in _quantile
    slices_having_nans = np.isnan(arr[-1, ...])
                                  ~~~^^^^^^^^^
IndexError: index -1 is out of bounds for axis 0 with size 0
